name: Update Spotify Now Playing

on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Spotify Now Playing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Spotify Now Playing
        uses: natemoo-re/action-spotify-now-playing@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_id: sakiidev
          embed_size: 400x100
          embed_theme: dark
          show_author: true
